feature(jv-input-controls): Cascading Input Controls
Jaspersoft/js-visualize-components pull request #96
Opened 2024-12-26 18:52 UTC by ecanchev-jaspersoft

This PR adds the feature for having cascading input controls. 
![PR-gif](https://github.com/user-attachments/assets/87cabf68-bf04-4579-b015-848b5542da15)

Additionally, the jv-tools package accepts an object when using the useVisualize custom hook to provide the server and the context path:

```
const vContainer = useVisualize(
    {
      server: "https://mobiledemo.jaspersoft.com",
      contextPath: "/jasperserver-pro",
    },
    myAuth,
    { errorCallback },
  );
```
this will add the server property to the vObject: 
![PR](https://github.com/user-attachments/assets/ffc97ba6-50c2-4c77-a921-5cac7b765c9d)

2024-12-26 21:44 UTC, yplakosh-jaspersoft commented
I propose to merge `server` and `contextPath` properties into one `server` property.

2024-12-26 23:40 UTC, ecanchev-jaspersoft commented
> I propose to merge `server` and `contextPath` properties into one `server` property.

both properties have been merged. 
Now, the `useVisualize `hook will accept: 
 ```
 const vContainer = useVisualize(
    {
      server: "https://mobiledemo.jaspersoft.com/jasperserver-pro",
      visualizePath:
        "https://mobiledemo.jaspersoft.com/jasperserver-pro/client/visualize.js",
      auth: {...},
    },
    { errorCallback },
  );
```

2025-01-02 23:31 UTC, grantbacon-jaspersoft requested changes

2025-01-02 23:31 UTC, grantbacon-jaspersoft commented on packages/jv-input-controls/src/utils/StringUtils.ts
> +    const endOfString = cIndex === dependencies.length - 1 ? "" : ";";
Can we just use `dependencies.join(';')` here?

2025-01-02 23:31 UTC, grantbacon-jaspersoft commented on packages/jv-tools/src/visualize/hooks/useVisualize.ts
> +            const finalVObject =
I don't know if we should be augmenting the v object in our own javascript, Perhaps we can instead return a tuple containing the v object and a metadata structure with these additional params

2025-01-03 16:58 UTC, ecanchev-jaspersoft commented on packages/jv-input-controls/src/reducer/InputControlsReducer.tsx
> +  switch (type) {
we can do that, however, this is the reducer. It is expected to have a switch (or maybe IF conditionals) per each **action**. 
Are we sure we want to change this to named methods?

2025-01-03 19:07 UTC, ecanchev-jaspersoft commented on packages/jv-tools/src/visualize/hooks/useVisualize.ts
> +            const finalVObject =
we discussed this internally and we agreed to extend the vObject only when is needed
hence, resolving this comment.

2025-01-03 22:58 UTC, grantbacon-jaspersoft approved these changes

2025-01-04 00:00 UTC, merged